# Main configuration file for the BedrockSkyBlock plugin.
# Some of these settings are safe, others can break your server if modified incorrectly.
# New settings/defaults won't appear automatically in this file when upgrading.

# The Language that this plugin will use.
# Available languages: eng
# For the language contributors, If you submit a new language translation, You should add it to the list of available languages.
language: eng
